# Generated by Django 4.0.5 on 2023-03-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_remove_createevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createevent',
            name='date_time',
            field=models.CharField(max_length=200),
        ),
    ]
